from __future__ import annotations

import pytest

from scripts.canary import owner_gate_firewall_readiness as firewall


def _save_output(*, chain=firewall.CHAINS[0], rules=None) -> str:
    if rules is None:
        rules = firewall.expected_rules(chain)
    return "\n".join((
        "# Generated by iptables-nft-save v1.8.9",
        "*filter",
        ":INPUT ACCEPT [1:2]",
        ":FORWARD ACCEPT [0:0]",
        ":OUTPUT ACCEPT [3:4]",
        f":{chain} - [0:0]",
        *rules,
        "COMMIT",
    )) + "\n"


def test_live_iptables_nft_projection_accepts_runtime_counters() -> None:
    projection = firewall.validate_live_ruleset(_save_output())
    assert projection["backend"] == "iptables-nft"
    assert projection["chain"] == firewall.CHAINS[0]
    assert projection["rules"] == list(
        firewall.expected_rules(firewall.CHAINS[0])
    )
    assert len(projection["projection_sha256"]) == 64


def test_live_iptables_nft_projection_accepts_alternate_generation() -> None:
    projection = firewall.validate_live_ruleset(
        _save_output(chain=firewall.CHAINS[1])
    )
    assert projection["chain"] == firewall.CHAINS[1]


def test_live_projection_binds_complete_ordered_output_after_first_jump() -> None:
    unrelated = "-A OUTPUT -d 203.0.113.9/32 -j ACCEPT"
    output = _save_output(rules=(*firewall.expected_rules(firewall.CHAINS[0]), unrelated))

    projection = firewall.validate_live_ruleset(output)

    assert projection["ordered_output_rules"] == [
        firewall.expected_rules(firewall.CHAINS[0])[0],
        unrelated,
    ]


@pytest.mark.parametrize(
    "rules",
    [
        (
            "-A OUTPUT -j ACCEPT",
            *firewall.expected_rules(firewall.CHAINS[0]),
        ),
        (
            f"-A OUTPUT -d {firewall.METADATA} -j ACCEPT",
            *firewall.expected_rules(firewall.CHAINS[0]),
        ),
        (
            *firewall.expected_rules(firewall.CHAINS[0]),
            firewall.expected_rules(firewall.CHAINS[0])[0],
        ),
        (
            *firewall.expected_rules(firewall.CHAINS[0]),
            f"-A OUTPUT -d {firewall.METADATA} -j ACCEPT",
        ),
        (
            *firewall.expected_rules(firewall.CHAINS[0]),
            f"-A OUTPUT -d {firewall.METADATA} -j {firewall.CHAINS[1]}",
        ),
    ],
)
def test_live_projection_rejects_earlier_bypass_or_duplicate_output_rule(
    rules,
) -> None:
    with pytest.raises(
        firewall.OwnerGateFirewallError,
        match="owner_gate_firewall_rules_invalid",
    ):
        firewall.validate_live_ruleset(_save_output(rules=rules))


@pytest.mark.parametrize(
    "rules",
    [
        firewall.expected_rules(firewall.CHAINS[0])[:-1],
        (
            *firewall.expected_rules(firewall.CHAINS[0]),
            f"-A {firewall.CHAINS[0]} -m owner --uid-owner 29101 -j RETURN",
        ),
        tuple(
            line.replace("29103", "29101")
            for line in firewall.expected_rules(firewall.CHAINS[0])
        ),
        tuple(
            line.replace("REJECT", "ACCEPT")
            for line in firewall.expected_rules(firewall.CHAINS[0])
        ),
    ],
)
def test_live_iptables_nft_projection_rejects_boundary_change(rules) -> None:
    with pytest.raises(firewall.OwnerGateFirewallError):
        firewall.validate_live_ruleset(_save_output(rules=rules))


def test_live_iptables_nft_projection_rejects_two_active_generations() -> None:
    output = _save_output() + "\n".join(
        firewall.expected_rules(firewall.CHAINS[1])
    )
    with pytest.raises(firewall.OwnerGateFirewallError):
        firewall.validate_live_ruleset(output)


def test_installer_uses_only_fixed_iptables_nft_commands(tmp_path) -> None:
    rules_path = tmp_path / "metadata-firewall.rules"
    rules_path.write_text(
        "\n".join(firewall.RULE_SOURCE_LINES) + "\n",
        encoding="ascii",
    )
    rules_path.chmod(0o444)
    calls = []
    delete_count = 0

    def run(argv):
        nonlocal delete_count
        calls.append(tuple(argv))
        if "-C" in argv:
            return 0 if argv[-1] == firewall.CHAINS[0] else 1
        if "-D" in argv:
            delete_count += 1
            return 0 if delete_count == 1 else 1
        return 0

    digest = firewall.install_firewall(
        rules_path=rules_path,
        runner=run,
        require_root=False,
        expected_source_uid=rules_path.stat().st_uid,
    )
    assert len(digest) == 64
    inactive = firewall.CHAINS[1]
    new_jump = next(
        index for index, call in enumerate(calls)
        if "-I" in call and call[-1] == inactive
    )
    append_indices = [
        index
        for index, call in enumerate(calls)
        if "-A" in call and call[call.index("-A") + 1] == inactive
    ]
    old_delete = next(index for index, call in enumerate(calls) if "-D" in call)
    assert tuple(calls[index] for index in append_indices) == tuple(
        (
            firewall.IPTABLES,
            "-w",
            "5",
            "-A",
            inactive,
            *rule,
        )
        for rule in firewall._rule_argv(inactive)
    )
    assert max(append_indices) < new_jump < old_delete
    assert all(call[0] == firewall.IPTABLES for call in calls)
    assert all("sh" not in call[0] for call in calls)


def test_installer_refuses_ambiguous_dual_generation(tmp_path) -> None:
    rules_path = tmp_path / "metadata-firewall.rules"
    rules_path.write_text(
        "\n".join(firewall.RULE_SOURCE_LINES) + "\n",
        encoding="ascii",
    )
    rules_path.chmod(0o444)

    def run(argv):
        return 0 if "-S" in argv or "-C" in argv else 1

    with pytest.raises(
        firewall.OwnerGateFirewallError,
        match="multiple_active_generations",
    ):
        firewall.install_firewall(
            rules_path=rules_path,
            runner=run,
            require_root=False,
            expected_source_uid=rules_path.stat().st_uid,
        )


def test_installer_bootstraps_when_both_managed_chains_are_absent(
    tmp_path: Path,
) -> None:
    rules_path = tmp_path / "metadata-firewall.rules"
    rules_path.write_text(
        "\n".join(firewall.RULE_SOURCE_LINES) + "\n",
        encoding="ascii",
    )
    rules_path.chmod(0o444)
    calls = []

    def run(argv):
        calls.append(tuple(argv))
        if "-S" in argv:
            return 1
        if "-C" in argv:
            raise AssertionError("absent jump target must not be checked")
        return 0

    digest = firewall.install_firewall(
        rules_path=rules_path,
        runner=run,
        require_root=False,
        expected_source_uid=rules_path.stat().st_uid,
    )
    assert len(digest) == 64
    assert tuple(call[-1] for call in calls if "-S" in call) == firewall.CHAINS
    assert not any("-C" in call for call in calls)
